[[Admin-API]]
== Admin API

[[Admin-유저-검색]]
=== Admin 유저 검색
operation::admin/searchUser[snippets='http-request,query-parameters,http-response']

[[Admin-유저-검색-권한-에러]]
=== Admin 유저 검색 (권한 에러)
operation::admin/searchUser/failByForbiddenError[snippets='http-request,request-headers,query-parameters,http-response']

[[Admin-유저-검색-존재하지-않는-유저-에러]]
=== Admin 유저 검색 (존재하지 않는 유저 에러)
operation::admin/searchUser/failByNotFoundError[snippets='http-request,request-headers,query-parameters,http-response']

[[Admin-유저-권한변경]]
=== Admin 유저 권한변경
operation::admin/changeUserRole[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[Admin-유저-권한변경-권한-에러]]
=== Admin 유저 권한변경 (권한 에러)
operation::admin/changeUserRole/failByForbiddenError[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[Admin-유저-권한변경-존재하지-않는-유저-에러]]
=== Admin 유저 권한변경 (존재하지 않는 유저 에러)
operation::admin/changeUserRole/failByNotFoundError[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[Admin-프로덕트-생성]]
=== Admin 프로덕트 생성
operation::product/create[snippets='http-request,request-headers,request-fields,http-response']

[[Admin-프로덕트-생성-권한-에러]]
=== Admin 프로덕트 생성 (권한 에러)
operation::product/create/failByForbiddenError[snippets='http-request,request-headers,request-fields,http-response']

[[Admin-프로덕트-상태변경]]
=== Admin 프로덕트 상태변경
operation::product/changeStatus[snippets='http-request,path-parameters,request-fields,http-response']

[[Admin-프로덕트-상태변경-권한-에러]]
=== Admin 프로덕트 상태변경 (권한 에러)
operation::product/changeStatus/failByForbiddenError[snippets='http-request,path-parameters,request-fields,http-response']

[[Admin-프로덕트-상태변경-존재하지-않는-프로덕트-에러]]
=== Admin 프로덕트 상태변경 (존재하지 않는 프로덕트 에러)
operation::product/changeStatus/failByNotFoundError[snippets='http-request,path-parameters,request-fields,http-response']

[[Admin-매거진-생성]]
=== Admin 매거진 생성
operation::magazine/create[snippets='http-request,request-headers,request-fields,http-response']

[[Admin-매거진-생성-권한-에러]]
=== Admin 매거진 생성 (권한 에러)
operation::magazine/create/failForbiddenError[snippets='http-request,request-headers,request-fields,http-response']

[[Admin-매거진-수정]]
=== Admin 매거진 수정
operation::magazine/update[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[Admin-매거진-수정-권한-에러]]
=== Admin 매거진 수정 (권한 에러)
operation::magazine/update/failForbiddenError[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[Admin-매거진-수정-존재하지-않는-매거진-에러]]
=== Admin 매거진 수정 (존재하지 않는 매거진 에러)
operation::magazine/update/failByNotFoundError[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

[[Admin-매거진-삭제]]
=== Admin 매거진-삭제
operation::magazine/delete[snippets='http-request,request-headers,path-parameters,http-response']

[[Admin-매거진-삭제-권한-에러]]
=== Admin 매거진 삭제 (권한 에러)
operation::magazine/delete/failByForbiddenError[snippets='http-request,request-headers,path-parameters,http-response']

[[Admin-매거진-삭제-존재하지-않는-매거진-에러]]
=== Admin 매거진 삭제 (존재하지 않는 매거진 에러)
operation::magazine/delete/failByNotFoundError[snippets='http-request,request-headers,path-parameters,http-response']