[[Auth-API]]
== Auth API

[[Auth-구글-로그인창-링크-생성]]
=== Auth 구글 로그인창 링크 생성
operation::auth/generateLink/google[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

[[Auth-카카오-로그인창-링크-생성]]
=== Auth 카카오 로그인창 링크 생성
operation::auth/generateLink/kakao[snippets='http-request,path-parameters,query-parameters,http-response,response-fields']

[[Auth-구글-로그인-요청]]
=== Auth 구글 로그인 요청
operation::auth/generateAccessAndRefreshToken/google[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[Auth-카카오-로그인-요청]]
=== Auth 카카오 로그인 요청
operation::auth/generateAccessAndRefreshToken/kakao[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[Auth-로그인-요청-OAuth-통신-에러]]
=== Auth 로그인 요청 (OAuth 통신 에러)
operation::auth/generateAccessAndRefreshToken/failByResourceServerError[snippets='http-request,path-parameters,request-fields,http-response']

[[Auth-엑세스토큰-재발급]]
=== Auth 엑세스토큰 재발급
operation::auth/generateRenewalAccessToken[snippets='http-request,request-fields,http-response,response-fields']

[[Auth-엑세스토큰-재발급-잘못된-리프래쉬토큰-에러]]
=== Auth 엑세스토큰 재발급 (잘못된 리프래쉬토큰 에러)
operation::auth/generateRenewalAccessToken/failByinvalidTokenError[snippets='http-request,request-fields,http-response']

[[Auth-엑세스토큰-재발급-만료된-리프래쉬토큰-에러]]
=== Auth 엑세스토큰 재발급 (만료된 리프래쉬토큰 에러)
operation::auth/generateRenewalAccessToken/failByExpireTokenError[snippets='http-request,request-fields,http-response']